/*
 * This source file was generated by the Gradle 'init' task
 */
package quiz1sistemasg2;

import java.util.Scanner;

public class App {
    
     


    
      
    public static void main(String[] args) {
    try {
        
        String tipoVehiculo = 0;
        int horasParqueadero = 0;
        String esEstudiante = 0;
       int montoParqueadero;
        int precioParqueadero;

     Scanner sc = new Scanner(System.in);
     //Preguntarle al usuario en que vehiculo vino
     System.out.println("Ingrese C para carro. Ingrese M para moto. Ingrese B para bicicleta.");
      tipoVehiculo = sc.nextLine();
      //Preguntarle al usuario cuantas horas permanecio en el parqueadero
      System.out.println("Cuantas horas estuvo en el parqueadero");
      horasParqueadero = sc.nextInt();
      sc.nextLine();
      //Solicitarle al usuario si es estudiante de
      System.out.println("Ingrese 1 si eres estudiante. Ingrese 2 para no");
      esEstudiante = sc.nextLine(); 
        
        
      
     

    } catch (Exception e) {
        
    }    
       

    }

    /*  Implemente una funcion llamada calcularValorHora que cumpla con las siguientes caracteristicas
        * Recibe: 
            - Una cadena de caracteres que representa el tipo de vehiculo (C, M o B)
            - Un entero que representa la cantidad de horas de permanencia
        * Retorna:
            - Un entero representando el valor total de las boletas
        * Controlar errores retornando -1
    */
    //------------------------------------------------------------------
    
    public int calcularValorHora(String tipoVehiculo, int horasParqueadero) {
        try {
            tipoVehiculo = Integer.parseInt(tipoVehiculo);
              switch (tipoVehiculo) {
                case "C":
                return  5000;
                    break;

                    break;
              }
              switch (tipoVehiculo) {
                case "M":
                return 3000;
            
                    
                       break;
              
                default:
                    break;
              }
              switch (tipoVehiculo) {
                case "B":
                    return 1000;
                    break;
              
                default:
                    break;
              }
            return -1;

            if (horasParqueadero > 3) {
            
                
            }
        } catch (Exception e) {
          return -1;
        }

    //------------------------------------------------------------------

    /*  Implemente una funcion llamada calcularDescuento que cumpla con las siguientes caracteristicas
        * Recibe:
            - Un entero representando el valor total de las horas
            - Un entero representando la si es estudiante o no
            - Un entero represenatando la cantidad de horas
        * Retorna:
            - Un entero representando el valor del descuento
        * Controlar errores retornando -1
    */
    //------------------------------------------------------------------
    public int calcularDescuento( esEstudiante, horasParqueadero);


    //------------------------------------------------------------------

    /*  Implemente una funcion llamada calcularFactura que cumpla con las siguientes caracteristicas
        * Recibe:
            - Un entero representando el valor total de las horas
            - Un entero representando el valor del descuento
        * Retorna:
            - Un entero representando el valor del total de la factura incluyendo el iva
    */
    //------------------------------------------------------------------
    


    //------------------------------------------------------------------
} }
